export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_ALL_NAMES = 'LOAD_ALL_NAMES';
export const LOAD_ALL_STUDENTS = 'LOAD_ALL_STUDENTS';
export const COMMIT_MAIN_AND_SUBMODULE_CHANGES = 'COMMIT_MAIN_AND_SUBMODULE_CHANGES';
export const COMMIT2_MAIN_AND_SUBMODULE_CHANGES = 'COMMIT2_MAIN_AND_SUBMODULE_CHANGES';