export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_ALL_NAMES = 'LOAD_ALL_NAMES';
export const LOAD_ALL_STUDENTS = 'LOAD_ALL_STUDENTS';
export const COMMIT_MAIN_AND_SUBMODULE_CHANGES = 'COMMIT_MAIN_AND_SUBMODULE_CHANGES';
export const COMMIT2_MAIN_AND_SUBMODULE_CHANGES = 'COMMIT2_MAIN_AND_SUBMODULE_CHANGES';
export const COMMIT3_MAIN_AND_SUBMODULE_CHANGES = 'COMMIT2_MAIN_AND_SUBMODULE_CHANGES';
export const COMMIT_SUBMODULE_ONLY = 'COMMIT_SUBMODULE_ONLY';
export const COMMIT_SUBMODULE_ONLY2 = 'COMMIT_SUBMODULE_ONLY2';
export const AFTER_TAG_CREATED_ON_PARENT_REPO = 'AFTER_TAG_CREATED_ON_PARENT_REPO';

export const TAG_RELEASE2 = 'TAG_RELEASE2.0';